### ISSUE TITLE
Плашка "потяните, чтобы обновить"

### ISSUE THREAD

**Issue by binidini** [binidini/tytymyty-android#4]
В доступных заказах добавить наверху плашку 
"Потяните, чтобы обновить"

См. приложение Достависты.

Сейчас не понятно новичку, как обновлять заказы.

**Comment by binidini** [comment]
Только что увидел кнопку обновить.  На данный этапе ее достаточно. Если  делать плашку больше 20 мин, можно отложить.

**Comment by allnimator** [comment]
Забил на плашку. Я поменял сам стиль рефреша. Надо обойтись без нее - лишнее место только занимает. Да и видел ее только в достависте. Мне нравится как сделано в вк. Там, если появляется что-то новое в ленте, появляется сверху текст "нажми, чтобы обновить". Ну а если хочешь еще, то можешь и тянуть
