### ISSUE TITLE
Добавить возможность добавлять заказы

### ISSUE THREAD

**Issue by binidini** [binidini/tytymyty-android#52]
С этой задачей придется переработать меню.
За основу взять сайт

**Comment by allnimator** [comment]
Сервер:
* метод на создание со всеми полями;
* валидация данных;
* загрузка картинки.

Клиент:
* пункты меню "Свои заказы"(активные и завершенные);
* список своих заказов:
 * все, что есть в других списках заказов;
 * метка статуса(активные, конфликтные и тд);
 * переход к конкретному заказу (такой же вид как и в остальных).
* кнопка "добавить":
 * поля из сайта;
 * возможность сделать фото или выбрать из галереи
 * подсказки для адресов:
 * взять подсказки из яндекса;
 * скрывать необязательные поля;
 * подсказки по полям (описания полей).
* статуса добавления заказа или переход в список.
