### ISSUE TITLE
подсказка адреса

### ISSUE THREAD

**Issue by binidini** [binidini/tytymyty-android#61]
сейчас работает не очень хорошо, хочется добиться  более информативных подсказок 
- больше вариантов
- сначала показывать варианты возле местоположения телефона

------------
На сайте считаю работает хорошо

--------------
Возможно есть ограничения, чтоб не тратить много трафика и ресурсов телефона, тогда
нужно обоснование, что текущая версия оптимальна.

**Comment by allnimator** [comment]
Так как отличаются ответы, то значит версия скрипта на сайте использует базу не такую как в яндекс-геокодере. На данный момент отображаются все адреса, которые приходят из апи-ответа за исключением названий рек, озер и тд. Остаются только "street", "locality", "house", "metro", "district"

**Comment by binidini** [comment]
посмотрел Андройд

подсказка адреса работает плохо

попытался ввести Московский проспект.  во-первых не было подсказки, во-вторых, если адреса нет в базе - а это часто бывает - то я не могу ввести адрес.

надо либо переделать, либо найти правильные настройки.

Нужна функциональность как на сайте.
