### ISSUE TITLE
карты для этого заказы не поддерживаются

### ISSUE THREAD

**Issue by binidini** [binidini/tytymyty-android#62]
не могу открыть карту маршрута

а хотелось бы видеть возможность смотреть маршрут и в гугле и в яндексе

**Comment by allnimator** [comment]
Здесь работает так:
1. я смотрю присланы ли координаты.
2. если есть то показываю карту(для маршрута должны быть оба адреса с координатами, при клике на конкретный адрес соотвествующий);
3. координаты у тебя проставляются воркером, соответственно он не может найти этот адрес.

Можно поменять уведомление. Типа "адрес не найдет", либо еще какой-либо. Адрес не найдет мне нравится больше, чем что сейчас.

**Comment by allnimator** [comment]
Почему то изменился формат ответа от сервера. Из-за этого и отвалилось.
